CREATE TABLE projects
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_manager_id BIGINT                                  NOT NULL,
    name               VARCHAR(255),
    description        VARCHAR(255),
    start_date         date,
    end_date           date,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id      BIGINT                                  NOT NULL,
    name            VARCHAR(255),
    description     VARCHAR(255),
    estimated_hours DOUBLE PRECISION,
    progress DOUBLE PRECISION,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE timesheet_entries
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_id       BIGINT,
    employee_name VARCHAR(255),
    hours_worked  DOUBLE PRECISION,
    work_date     date,
    notes         VARCHAR(255),
    submitted_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_timesheet_entries PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       SMALLINT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_PROJECT_MANAGER FOREIGN KEY (project_manager_id) REFERENCES users (id);

CREATE INDEX idx_tasks_project_id ON tasks(project_id);
CREATE INDEX idx_timesheet_entries_task_id ON timesheet_entries(task_id);
CREATE INDEX idx_timesheet_entries_work_date ON timesheet_entries(work_date);

